// Engine-level testbench for slh_verify (SLH-DSA-SHA2-128s).
//
// Streams pre-signed license vectors (generated by tools/gen_slh_vectors.py)
// into the bare verification engine and checks accept/reject behaviour:
//   1. genuine license                          -> accepted
//   2. same license again (engine re-use)       -> accepted
//   3. genuine license with random stream gaps  -> accepted
//   4. tampered R element (beat 0)              -> rejected
//   5. tampered FORS element                    -> rejected
//   6. tampered hypertree element               -> rejected
//   7. tampered final auth sibling (last beat)  -> rejected
//   8. wrong message (nonce bit flipped)        -> rejected
//
// Every run must consume exactly SLH_SIG_ELEMS beats; a watchdog kills a
// stalled run.

module tb (
    input logic clk,
    input logic rst_n
);
    import slh_pkg::*;

    localparam int unsigned NUM_BEATS = SLH_SIG_ELEMS;  // 491
    localparam int unsigned TIMEOUT   = 3_000_000;

    // -------------------------------------------------------------------------
    // Vectors
    // -------------------------------------------------------------------------

    logic [SLH_BEAT_W-1:0] beats [0:NUM_BEATS-1];
    logic [255:0]          msg_mem [0:0];

    // Paths are relative to verilog/ (make sim runs the binary from there)
    initial begin
        $readmemh("tb/vectors/slh128s/license_beats.hex", beats);
        $readmemh("tb/vectors/slh128s/message.hex", msg_mem);
    end

    // -------------------------------------------------------------------------
    // DUT
    // -------------------------------------------------------------------------

    logic [255:0]          message;
    logic                  valid;
    wire                   ready;
    logic [SLH_BEAT_W-1:0] data;
    wire                   verify_done;
    wire                   verif_passed;

    hbsv_verify #(
        .SCH (hbsv_ctrl_pkg::SCHEME_SLH)
    ) u_dut (
        .clk          (clk),
        .rst_n        (rst_n),
        .message      (message),
        .key_ctx      (SLH_KEYS[0].seed),
        .root         (SLH_KEYS[0].root),
        .midstate     (SLH_KEYS[0].midstate),
        .valid        (valid),
        .ready        (ready),
        .data         (data),
        .verify_done  (verify_done),
        .verif_passed (verif_passed)
    );

    // -------------------------------------------------------------------------
    // Stream driver
    // -------------------------------------------------------------------------

    int unsigned n_pass, n_fail;
    logic [15:0] gap_lfsr;

    task automatic load_vectors(input string dir);
        $readmemh({dir, "/license_beats.hex"}, beats);
        $readmemh({dir, "/message.hex"}, msg_mem);
    endtask

    task automatic run_case(
        input string       name,
        input bit          exp_pass,
        input int          tamper_beat,   // -1 = none
        input int          tamper_bit,
        input bit          tamper_msg,
        input bit          gaps
    );
        int unsigned sent;
        int unsigned cycles;
        logic [SLH_BEAT_W-1:0] beat;
        bit done_seen, passed;

        message = msg_mem[0] ^ (tamper_msg ? 256'h1 << 77 : 256'h0);
        valid   = 1'b0;
        data    = '0;
        sent    = 0;
        cycles  = 0;
        done_seen = 1'b0;
        passed    = 1'b0;
        gap_lfsr  = 16'hACE1;

        @(negedge clk);

        while (!done_seen && cycles < TIMEOUT) begin
            // Present the next beat, optionally with gaps
            if (sent < NUM_BEATS) begin
                gap_lfsr = {gap_lfsr[14:0], gap_lfsr[15] ^ gap_lfsr[13]
                                          ^ gap_lfsr[12] ^ gap_lfsr[10]};
                if (!gaps || gap_lfsr[0]) begin
                    beat = beats[sent];
                    if (int'(sent) == tamper_beat) beat = beat ^ (128'h1 << tamper_bit);
                    valid = 1'b1;
                    data  = beat;
                end else begin
                    valid = 1'b0;
                    data  = 'x;
                end
            end else begin
                valid = 1'b0;
                data  = '0;
            end

            @(posedge clk);
            if (valid && ready) sent++;
            if (verify_done) begin
                done_seen = 1'b1;
                passed    = verif_passed;
            end
            @(negedge clk);
            cycles++;
        end

        if (!done_seen) begin
            $display("FAIL  %s: timeout after %0d cycles (%0d/%0d beats consumed)",
                     name, cycles, sent, NUM_BEATS);
            n_fail++;
        end else if (sent != NUM_BEATS) begin
            $display("FAIL  %s: consumed %0d beats, expected %0d",
                     name, sent, NUM_BEATS);
            n_fail++;
        end else if (passed != exp_pass) begin
            $display("FAIL  %s: verif_passed=%0d, expected %0d",
                     name, passed, exp_pass);
            n_fail++;
        end else begin
            $display("PASS  %s (%0d cycles)", name, cycles);
            n_pass++;
        end
    endtask

    // -------------------------------------------------------------------------
    // Test sequence
    // -------------------------------------------------------------------------

    initial begin
        message = '0;
        valid   = 1'b0;
        data    = '0;
        n_pass  = 0;
        n_fail  = 0;

        wait (rst_n === 1'b0);
        wait (rst_n === 1'b1);
        repeat (4) @(negedge clk);

        run_case("genuine license",            1'b1, -1,  0, 1'b0, 1'b0);
        run_case("engine re-use",              1'b1, -1,  0, 1'b0, 1'b0);
        run_case("stream gaps",                1'b1, -1,  0, 1'b0, 1'b1);
        run_case("tampered R",                 1'b0,  0, 17, 1'b0, 1'b0);
        run_case("tampered FORS element",      1'b0, 10, 63, 1'b0, 1'b0);
        run_case("tampered HT element",        1'b0, 300, 5, 1'b0, 1'b0);
        run_case("tampered last auth sibling", 1'b0, NUM_BEATS-1, 90, 1'b0, 1'b0);
        run_case("wrong message",              1'b0, -1,  0, 1'b1, 1'b0);

        // Edge-digit vector sets: messages chosen so some layer's chain-34
        // digit is 15 (skip path at the T_35-closing absorb slot) or 0
        // (maximum-length chain there) — rare paths a single vector can miss.
        load_vectors("tb/vectors/slh128s_edge15");
        run_case("edge: chain-34 digit 15",    1'b1, -1,  0, 1'b0, 1'b0);
        load_vectors("tb/vectors/slh128s_edge0");
        run_case("edge: chain-34 digit 0",     1'b1, -1,  0, 1'b0, 1'b0);

        $display("----------------------------------------");
        $display("tb_slh_verify: %0d passed, %0d failed", n_pass, n_fail);
        if (n_fail != 0) $fatal(1, "tb_slh_verify FAILED");
        $finish;
    end

endmodule
