package hss_pkg;

    import arith_pkg::*;

    // -------------------------------------------------------------------------
    // RFC 8554 domain separation constants
    // -------------------------------------------------------------------------

    localparam logic [15:0] D_MESG = 16'h8181;
    localparam logic [15:0] D_PBLC = 16'h8080;
    localparam logic [15:0] D_LEAF = 16'h8282;
    localparam logic [15:0] D_INTR = 16'h8383;

    // -------------------------------------------------------------------------
    // RFC 8554 typecodes
    // -------------------------------------------------------------------------

    // RFC 8554 §5.1 LMS / LM-OTS typecodes  — embedded in inter-layer signed pub.
    // Values only need to agree between signer and verifier; RFC registry values
    // are used as reasonable defaults.

    typedef enum logic[31:0] {
        LMOTS_RESERVED       = 0,
        LMOTS_SHA256_N32_W1  = 1,
        LMOTS_SHA256_N32_W2  = 2,
        LMOTS_SHA256_N32_W4  = 3,
        LMOTS_SHA256_N32_W8  = 4
    } lmots_algorithm_t;

    typedef enum logic[31:0] {
        LMS_RESERVED       = 0,
        LMS_SHA256_N32_H5  = 5,
        LMS_SHA256_N32_H10 = 6,
        LMS_SHA256_N32_H15 = 7,
        LMS_SHA256_N32_H20 = 8,
        LMS_SHA256_N32_H25 = 9
    } lms_algorithm_t;

    // -------------------------------------------------------------------------
    // Fixed parameters for simplification
    // -------------------------------------------------------------------------

    // Note: w could vary for each layer of the tree stack according to the standard.
    //       But implementation fixes it for simplicity.
    localparam int unsigned      WOTS_W      = 8;                     // Winternitz parameter
    localparam lmots_algorithm_t LMOTS_TYPE  = LMOTS_SHA256_N32_W8;   // LMOTS algorithm identifier
    localparam int unsigned      WOTS_P1     = 32;                    // data digits per chain
    localparam int unsigned      WOTS_P2     = 2;                     // checksum digits per chain


    // Note: h could vary for each layer of the tree stack according to the standard.
    //       But implementation fixes it for simplicity.
    localparam int unsigned    TREE_H      = 5;
    localparam lms_algorithm_t LMS_TYPE    = LMS_SHA256_N32_H5;    // LMS algorithm identifier
    /* verilator lint_off UNUSEDPARAM */
    localparam int unsigned    TREE_H_MAX  = 25;                   // max of lms_algorithm_type
    /* verilator lint_on UNUSEDPARAM */

    // Note: HSS levels could vary per signer according to the standard.
    //       But implementation fixes it for simplicity.
    localparam int unsigned HSS_LEVELS  = 2;

    // -------------------------------------------------------------------------
    // Public keys (HSS layers, top-tree identity, and root hash per signer)
    // -------------------------------------------------------------------------

    // Width of the per-tree identifier (RFC 8554: I is 16 bytes)
    localparam int unsigned IDENT_W = 128;

    typedef struct packed {
        // number of levels in the hypertree - fixed for simplification (see HSS_LEVELS)
        logic [31:0]        l;
        // TODO separate key into two layers: hss_public_key and lms_public_key as per RFC-8554
        // LMS algorithm identifier - fixed for simplification (see LMS_TYPE)
        lms_algorithm_t     lms_type;     // 'type' is a reserved SV keyword
        // LMOTS algorithm identifier - fixed for simplification (see LMOTS_TYPE)
        lmots_algorithm_t   otstype;
        // TODO use naming convention from RFC-8554
        logic [IDENT_W-1:0] identifier;
        logic [WIDTH-1:0]   root_pub_key;
    } pubkey_t;

    // Values must match tb/tb_hss_tree_pkg.sv (auto-generated by reference_lms.py).
    // identifier / root_pub_key are the top-tree (layer 0) identity of each
    // signer's hypertree; lower-layer identifiers travel in license.sub_I.
    parameter pubkey_t PUBKEYS [2] = '{
        // Signer 0
        0: '{l:            HSS_LEVELS,
             lms_type:     LMS_TYPE,
             otstype:      LMOTS_TYPE,
             identifier:   128'h01010101_01010101_01010101_01010101,
             root_pub_key: 256'h0d5d8e8b6c4eb1f474f02048e9cbecbeb66eb10fd307ea7d86f5d485b2e9b45f},
        // Signer 1
        1: '{l:            HSS_LEVELS,
             lms_type:     LMS_TYPE,
             otstype:      LMOTS_TYPE,
             identifier:   128'h11111111_11111111_11111111_11111111,
             root_pub_key: 256'h9b395083685f54e20a7f77a76e8ff2317e514ff2e6bbbaec942f80c872038167}
    };

    // -------------------------------------------------------------------------
    // Derived parameters
    // -------------------------------------------------------------------------

    // Derived values kept for the LMS testbenches and documentation
    /* verilator lint_off UNUSEDPARAM */
    // layer counter width
    localparam int unsigned LAYER_CNT_W = (HSS_LEVELS>1) ? $clog2(HSS_LEVELS) : 1;

    // total digits per chain
    localparam int unsigned WOTS_P = WOTS_P1 + WOTS_P2;

    // WOTS digit maximum value (all 1s)
    localparam logic [WOTS_W-1:0] WOTS_MAX_COEF = '1;
    /* verilator lint_on UNUSEDPARAM */

    // -------------------------------------------------------------------------
    // HSS-LMS license format
    // -------------------------------------------------------------------------
    // The license is streamed into hss_verify one WIDTH-bit beat at a time, in
    // the field order of the standard signature format. Per layer, from
    // HSS_LEVELS-1 down to 0:
    //
    //   beat 0        {leaf_index[32], sub_I[128], padding}   (RFC: q and I)
    //   beat 1        randomizer                              (RFC: C)
    //   beats 2..     WOTS_P chain signatures                 (RFC: y[])
    //   last TREE_H   authentication path siblings            (RFC: path[])
    //
    // Nothing is buffered up front: each beat is consumed where it is needed,
    // so the verifier only holds the current layer's identity. The full struct
    // lives with the signer in tb/tb_hss_sign_pkg.sv.
    /* verilator lint_off UNUSEDPARAM */
    localparam int unsigned LAYER_HDR_BEATS = 2;
    /* verilator lint_on UNUSEDPARAM */

    // -------------------------------------------------------------------------
    // Hash-message layouts (RFC 8554 field order, first byte in the MSBs).
    // Consumed by hbsv_schs_pkg; every message is I || q || ... so the
    // 22-byte prefix is shared.
    // -------------------------------------------------------------------------

    typedef struct packed {
        logic [IDENT_W-1:0] i;
        logic [31:0]        q;
        logic [15:0]        d;      // D_MESG / D_PBLC / D_LEAF
    } lms_prefix_t;                                             // 176 b

    typedef struct packed {          // Q, message layer: prefix || C || message
        lms_prefix_t      pre;
        logic [WIDTH-1:0] c;
        logic [WIDTH-1:0] msg;
    } lms_q_msg_t;                                              // 688 b

    typedef struct packed {          // Q, upper layers: prefix || C || serialised pubkey below
        lms_prefix_t        pre;
        logic [WIDTH-1:0]   c;
        logic [31:0]        lms_type;
        logic [31:0]        lmots_type;
        logic [IDENT_W-1:0] sub_i;
        logic [WIDTH-1:0]   root;
    } lms_q_sub_msg_t;                                          // 880 b

    typedef struct packed {          // WOTS chain step: I || q || u16(i) || u8(j) || tmp
        logic [IDENT_W-1:0] i;
        logic [31:0]        q;
        logic [15:0]        chain;
        logic [7:0]         step;
        logic [WIDTH-1:0]   tmp;
    } lms_chain_msg_t;                                          // 440 b

    typedef struct packed {          // leaf: I || q || D_LEAF || Kc
        lms_prefix_t      pre;
        logic [WIDTH-1:0] kc;
    } lms_leaf_msg_t;                                           // 432 b

    typedef struct packed {          // interior node: I || u32(node) || D_INTR || left || right
        logic [IDENT_W-1:0] i;
        logic [31:0]        node;
        logic [15:0]        d;
        logic [WIDTH-1:0]   left;
        logic [WIDTH-1:0]   right;
    } lms_intr_msg_t;                                           // 688 b

endpackage
