package hss_pkg;

    import arith_pkg::*;

    // -------------------------------------------------------------------------
    // RFC 8554 domain separation constants
    // -------------------------------------------------------------------------

    localparam logic [15:0] D_MESG = 16'h8181;
    localparam logic [15:0] D_PBLC = 16'h8080;
    localparam logic [15:0] D_LEAF = 16'h8282;
    localparam logic [15:0] D_INTR = 16'h8383;

    // -------------------------------------------------------------------------
    // RFC 8554 typecodes
    // -------------------------------------------------------------------------

    // RFC 8554 §5.1 LMS / LM-OTS typecodes  — embedded in inter-layer signed pub.
    // Values only need to agree between signer and verifier; RFC registry values
    // are used as reasonable defaults.

    typedef enum logic[31:0] {
        LMOTS_RESERVED       = 0,
        LMOTS_SHA256_N32_W1  = 1,
        LMOTS_SHA256_N32_W2  = 2,
        LMOTS_SHA256_N32_W4  = 3,
        LMOTS_SHA256_N32_W8  = 4
    } lmots_algorithm_t;

    typedef enum logic[31:0] {
        LMS_RESERVED       = 0,
        LMS_SHA256_N32_H5  = 5,
        LMS_SHA256_N32_H10 = 6,
        LMS_SHA256_N32_H15 = 7,
        LMS_SHA256_N32_H20 = 8,
        LMS_SHA256_N32_H25 = 9
    } lms_algorithm_t;

    // -------------------------------------------------------------------------
    // Fixed parameters for simplification
    // -------------------------------------------------------------------------

    // Note: w could vary for each layer of the tree stack according to the standard.
    //       But implementation fixes it for simplicity.
    localparam int unsigned      WOTS_W      = 8;                     // Winternitz parameter
    localparam lmots_algorithm_t LMOTS_TYPE  = LMOTS_SHA256_N32_W8;   // LMOTS algorithm identifier
    localparam int unsigned      WOTS_P1     = 32;                    // data digits per chain
    localparam int unsigned      WOTS_P2     = 2;                     // checksum digits per chain


    // Note: h could vary for each layer of the tree stack according to the standard.
    //       But implementation fixes it for simplicity.
    localparam int unsigned    TREE_H      = 5;
    localparam lms_algorithm_t LMS_TYPE    = LMS_SHA256_N32_H5;    // LMS algorithm identifier

    // Note: HSS levels could vary per signer according to the standard.
    //       But implementation fixes it for simplicity.
    localparam int unsigned HSS_LEVELS  = 2;

    // -------------------------------------------------------------------------
    // Public keys (HSS layers, top-tree identity, and root hash per signer)
    // -------------------------------------------------------------------------

    // Width of the per-tree identifier (RFC 8554: I is 16 bytes)
    localparam int unsigned IDENT_W = 128;

    typedef struct packed {
        // number of levels in the hypertree - fixed for simplification (see HSS_LEVELS)
        logic [31:0]        l;
        // TODO separate key into two layers: hss_public_key and lms_public_key as per RFC-8554
        // LMS algorithm identifier - fixed for simplification (see LMS_TYPE)
        lms_algorithm_t     lms_type;     // 'type' is a reserved SV keyword
        // LMOTS algorithm identifier - fixed for simplification (see LMOTS_TYPE)
        lmots_algorithm_t   otstype;
        // TODO use naming convention from RFC-8554
        logic [IDENT_W-1:0] identifier;
        logic [WIDTH-1:0]   root_pub_key;
    } pubkey_t;

    // Values must match tb/tb_hss_tree_pkg.sv (auto-generated by reference_lms.py).
    // identifier / root_pub_key are the top-tree (layer 0) identity of each
    // signer's hypertree; lower-layer identifiers travel in license.sub_I.
    parameter pubkey_t PUBKEYS [2] = '{
        // Signer 0
        0: '{l:            HSS_LEVELS,
             lms_type:     LMS_TYPE,
             otstype:      LMOTS_TYPE,
             identifier:   128'h01010101_01010101_01010101_01010101,
             root_pub_key: 256'h0d5d8e8b6c4eb1f474f02048e9cbecbeb66eb10fd307ea7d86f5d485b2e9b45f},
        // Signer 1
        1: '{l:            HSS_LEVELS,
             lms_type:     LMS_TYPE,
             otstype:      LMOTS_TYPE,
             identifier:   128'h11111111_11111111_11111111_11111111,
             root_pub_key: 256'h9b395083685f54e20a7f77a76e8ff2317e514ff2e6bbbaec942f80c872038167}
    };

    // -------------------------------------------------------------------------
    // Derived parameters
    // -------------------------------------------------------------------------

    // layer counter width
    localparam int unsigned LAYER_CNT_W = (HSS_LEVELS>1) ? $clog2(HSS_LEVELS) : 1;

    // total digits per chain
    localparam int unsigned WOTS_P = WOTS_P1 + WOTS_P2;

    // WOTS digit maximum value (all 1s)
    localparam logic [WOTS_W-1:0] WOTS_MAX_COEF = '1;

    // -------------------------------------------------------------------------
    // HSS-LMS license format
    // -------------------------------------------------------------------------

    typedef struct packed {
        // Per-layer metadata only. lv=0 is the top tree; lv=HSS_LEVELS-1 is
        // the leaf tree that signs the user message. The bulky material (WOTS+
        // sig chains and Merkle auth path) is not part of this struct; it
        // arrives on the hss_verify 256-bit element stream instead.
        //    Dimension 3     Dimension 2     Dimension 1
        logic [HSS_LEVELS-1:0]                [31:0]       leaf_index;
        logic [HSS_LEVELS-1:0]                [WIDTH-1:0]  randomizer;
        // Subtree identifiers. sub_I[0] is unused
        // (the top tree uses TOP_IDENTIFIER)
        logic [HSS_LEVELS-1:0]                [127:0]      sub_I;
    } license_t;

endpackage
