// Generated by gen_slh_vectors.py -- do not edit.
localparam int unsigned SLH_NUM_KEYS = 2;
localparam slh_key_t SLH_KEYS [SLH_NUM_KEYS] = '{
    '{seed: 128'h9e28978d02fa18bf8edc50912b94820b, root: 128'hb3170cb691200f4da7255edaac482a67, midstate: 256'h199c7f4d75d201cdebb5e8333f3eea263ab2fe7a0c43270fd1aade3fe79876a5},
    '{seed: 128'h269a0d804983087c48a885a3e02a0bf7, root: 128'hbd5e8c8a67c8966dccc92cfc6f05575b, midstate: 256'h2ceb7adec530fe115c10db4d176c09ebc49fe3e59e4ead60c834df18d7faaa7d}
};
