// SLH-DSA-SHA2-128s (FIPS 205) parameter package — Phase 1 LOW profile.
//
// Security category 1: every hash function is SHA-256 (FIPS 205 §11.2.1) and
// node values are n = 16 bytes. The HIGH profile (SHA2-256s, §11.2.2) is a
// planned parameter lift of this package — widths here are already written in
// terms of the Table 2 row where practical.

package slh_pkg;

    // -------------------------------------------------------------------------
    // FIPS 205 Table 2 row: SLH-DSA-SHA2-128s
    // -------------------------------------------------------------------------

    localparam int unsigned SLH_N    = 16;  // security parameter (bytes per node)
    localparam int unsigned SLH_H    = 63;  // hypertree height
    localparam int unsigned SLH_D    = 7;   // hypertree layers
    localparam int unsigned SLH_HP   = 9;   // h' = per-layer XMSS tree height
    localparam int unsigned SLH_A    = 12;  // FORS tree height
    localparam int unsigned SLH_K    = 14;  // FORS trees
    // Documentation constants (referenced by testbenches and tools)
    /* verilator lint_off UNUSEDPARAM */
    localparam int unsigned SLH_LGW  = 4;   // lg(w), w = 16
    localparam int unsigned SLH_M    = 30;  // H_msg output bytes
    /* verilator lint_on UNUSEDPARAM */

    // Derived (§5): len1 = 8n/lg_w, len2 = 3 for lg_w = 4, len = len1 + len2
    localparam int unsigned SLH_LEN1 = 32;
    localparam int unsigned SLH_LEN2 = 3;
    localparam int unsigned SLH_LEN  = SLH_LEN1 + SLH_LEN2;  // 35 WOTS chains

    // Node width in bits
    localparam int unsigned SLH_NW = 8 * SLH_N;  // 128

    // Digest split widths (Alg 20 lines 9-13)
    localparam int unsigned SLH_MD_W       = SLH_K * SLH_A;   // 168 = ceil(k*a/8)*8 exactly
    localparam int unsigned SLH_IDX_TREE_W = SLH_H - SLH_HP;  // 54
    localparam int unsigned SLH_IDX_LEAF_W = SLH_HP;          // 9

    // -------------------------------------------------------------------------
    // License stream geometry: one 16-byte signature element per beat, in
    // signature order (Fig 17): R, then k*(1+a) FORS elements, then per layer
    // len WOTS sig elements followed by h' auth siblings.
    // -------------------------------------------------------------------------

    localparam int unsigned SLH_BEAT_W     = SLH_NW;  // 128
    /* verilator lint_off UNUSEDPARAM */
    localparam int unsigned SLH_SIG_ELEMS  = 1 + SLH_K * (1 + SLH_A)
                                               + SLH_D * (SLH_LEN + SLH_HP);  // 491
    /* verilator lint_on UNUSEDPARAM */

    // -------------------------------------------------------------------------
    // ADRS types used in verification (§4.2; PRF types 5/6 are signing-only)
    // -------------------------------------------------------------------------

    localparam logic [7:0] ADRS_WOTS_HASH  = 8'd0;
    localparam logic [7:0] ADRS_WOTS_PK    = 8'd1;
    localparam logic [7:0] ADRS_TREE       = 8'd2;
    localparam logic [7:0] ADRS_FORS_TREE  = 8'd3;
    localparam logic [7:0] ADRS_FORS_ROOTS = 8'd4;

    // Compressed address width (§11.2, Fig 18): layer(1) tree(8) type(1) + 12
    /* verilator lint_off UNUSEDPARAM */
    localparam int unsigned SLH_ADRSC_W = 8 * 22;  // 176
    /* verilator lint_on UNUSEDPARAM */

    // -------------------------------------------------------------------------
    // Per-signer public-key material. The SHA-256 midstate of the constant
    // first block (PK.seed || 48 zero bytes) is precomputed offline, so
    // PK.seed itself is only ever hashed raw inside H_msg.
    // -------------------------------------------------------------------------

    typedef struct packed {
        logic [SLH_NW-1:0] seed;      // PK.seed
        logic [SLH_NW-1:0] root;      // PK.root
        logic [255:0]      midstate;  // SHA-256 state after (PK.seed || 0^48)
    } slh_key_t;

    // SLH_NUM_KEYS / SLH_KEYS — generated by tools/gen_slh_vectors.py
    `include "slh_keys.svh"

    // -------------------------------------------------------------------------
    // Hash-message layouts (§11.2.1; first byte in the MSBs). Everything
    // after H_msg follows the constant block PK.seed || 0^48, which is
    // precomputed as a midstate, so these carry only ADRSc || M.
    // -------------------------------------------------------------------------

    typedef struct packed {          // compressed address (§11.2, Fig 18)
        logic [7:0]  layer;
        logic [63:0] tree;
        logic [7:0]  typ;
        logic [31:0] kp;             // key-pair address
        logic [31:0] w6;             // chain address / tree height
        logic [31:0] w7;             // hash address / tree index
    } slh_adrs_c_t;                                             // 176 b

    typedef struct packed {          // F: ADRSc || M1
        slh_adrs_c_t       adrs;
        logic [SLH_NW-1:0] m1;
    } slh_f_msg_t;                                              // 304 b

    typedef struct packed {          // H: ADRSc || left || right
        slh_adrs_c_t       adrs;
        logic [SLH_NW-1:0] left;
        logic [SLH_NW-1:0] right;
    } slh_tree_msg_t;                                           // 432 b

    typedef struct packed {          // H_msg inner: R || PK.seed || PK.root || 0x0000 || M
        logic [SLH_NW-1:0] r;
        logic [SLH_NW-1:0] seed;
        logic [SLH_NW-1:0] root;
        logic [15:0]       pre;      // pure mode, empty context
        logic [255:0]      m;
    } slh_hmsg_msg_t;                                           // 656 b

    typedef struct packed {          // H_msg outer (MGF1, counter 0): R || PK.seed || inner || ctr
        logic [SLH_NW-1:0] r;
        logic [SLH_NW-1:0] seed;
        logic [255:0]      inner;
        logic [31:0]       ctr;
    } slh_mgf_msg_t;                                            // 544 b

endpackage
