// SLH-DSA-SHA2-128s (FIPS 205) parameter package.
//
// Security category 1: every hash function is SHA-256 (FIPS 205 11.2.1) and
// node values are n = 16 bytes. The other SHA2 parameter sets are a lift of
// this package; widths are written in terms of the Table 2 row where
// practical.

package slh_pkg;

    // -------------------------------------------------------------------------
    // FIPS 205 Table 2 row: SLH-DSA-SHA2-128s
    // -------------------------------------------------------------------------

    localparam int unsigned SLH_N   = 16;  // security parameter (bytes per node)
    localparam int unsigned SLH_H   = 63;  // hypertree height
    localparam int unsigned SLH_D   = 7;   // hypertree layers
    localparam int unsigned SLH_HP  = 9;   // h', the XMSS tree height
    localparam int unsigned SLH_A   = 12;  // FORS tree height
    localparam int unsigned SLH_K   = 14;  // FORS trees
    localparam int unsigned SLH_LGW = 4;   // lg(w), w = 16
    /* verilator lint_off UNUSEDPARAM */
    localparam int unsigned SLH_M   = 30;  // H_msg output bytes
    /* verilator lint_on UNUSEDPARAM */

    // Derived (5.1): len1 = 8n / lg_w, len2 = 3 for lg_w = 4
    localparam int unsigned SLH_LEN1 = 32;
    localparam int unsigned SLH_LEN2 = 3;
    localparam int unsigned SLH_LEN  = SLH_LEN1 + SLH_LEN2;

    // Node width in bits
    localparam int unsigned SLH_NW = 8 * SLH_N;

    // Digest split widths (Alg 20 lines 9-13); k * a is a multiple of 8 here
    localparam int unsigned SLH_MD_W       = SLH_K * SLH_A;
    localparam int unsigned SLH_IDX_TREE_W = SLH_H - SLH_HP;
    localparam int unsigned SLH_IDX_LEAF_W = SLH_HP;

    // -------------------------------------------------------------------------
    // License stream: one signature element per beat, in signature order
    // (Fig 17): R, then k * (1 + a) FORS elements, then per layer len WOTS
    // elements followed by h' auth-path siblings.
    // -------------------------------------------------------------------------

    localparam int unsigned SLH_BEAT_W    = SLH_NW;
    /* verilator lint_off UNUSEDPARAM */
    localparam int unsigned SLH_SIG_ELEMS = 1 + SLH_K * (1 + SLH_A) + SLH_D * (SLH_LEN + SLH_HP);
    /* verilator lint_on UNUSEDPARAM */

    // -------------------------------------------------------------------------
    // Per-signer public key
    // -------------------------------------------------------------------------

    typedef struct packed {
        logic [SLH_NW-1:0] seed;  // PK.seed
        logic [SLH_NW-1:0] root;  // PK.root
    } slh_key_t;

    // SLH_NUM_KEYS / SLH_KEYS — generated by tools/gen_slh_vectors.py
    `include "slh_keys.svh"

    // -------------------------------------------------------------------------
    // Address (4.2, 4.3) and hash-message layouts (11.2.1; first byte in the
    // MSBs)
    // -------------------------------------------------------------------------

    // ADRS types used in verification (PRF types 5 and 6 are signing-only)
    localparam int unsigned ADRS_TYPE_W = 8;
    localparam logic [ADRS_TYPE_W-1:0] ADRS_WOTS_HASH  = 0;
    localparam logic [ADRS_TYPE_W-1:0] ADRS_WOTS_PK    = 1;
    localparam logic [ADRS_TYPE_W-1:0] ADRS_TREE       = 2;
    localparam logic [ADRS_TYPE_W-1:0] ADRS_FORS_TREE  = 3;
    localparam logic [ADRS_TYPE_W-1:0] ADRS_FORS_ROOTS = 4;

    // Compressed address ADRSc (Fig 18): the layer and tree addresses
    // shortened to one and eight bytes, then the type and three words whose
    // meaning depends on it
    localparam int unsigned ADRS_LAYER_W = 8;
    localparam int unsigned ADRS_TREE_W  = 64;
    localparam int unsigned ADRS_WORD_W  = 32;

    typedef struct packed {
        logic [ADRS_LAYER_W-1:0] layer_addr;
        logic [ADRS_TREE_W-1:0]  tree_addr;
        logic [ADRS_TYPE_W-1:0]  adrs_type;
        logic [ADRS_WORD_W-1:0]  keypair_addr;
        logic [ADRS_WORD_W-1:0]  chain_or_height;  // chain address (WOTS_HASH), else tree height
        logic [ADRS_WORD_W-1:0]  hash_or_index;    // hash address (WOTS_HASH), else tree index
    } slh_adrs_c_t;

    // Every F, H and T_l message opens with PK.seed, zero-padded to a whole
    // SHA-256 block
    localparam int unsigned SEED_PAD_W = sha2_wrap_pkg::SHA256_BLOCK_W - SLH_NW;

    typedef struct packed {
        logic [SLH_NW-1:0]     seed;
        logic [SEED_PAD_W-1:0] zero_pad;
    } slh_seed_block_t;

    // F: PK.seed block || ADRSc || M1
    typedef struct packed {
        slh_seed_block_t   seed_block;
        slh_adrs_c_t       adrs;
        logic [SLH_NW-1:0] m1;
    } slh_f_msg_t;

    // H: PK.seed block || ADRSc || left || right
    typedef struct packed {
        slh_seed_block_t   seed_block;
        slh_adrs_c_t       adrs;
        logic [SLH_NW-1:0] left;
        logic [SLH_NW-1:0] right;
    } slh_h_msg_t;

    // T_l: PK.seed block || ADRSc, followed by the l values
    typedef struct packed {
        slh_seed_block_t   seed_block;
        slh_adrs_c_t       adrs;
    } slh_t_prefix_t;

    // H_msg, inner hash: R || PK.seed || PK.root || M', where M' opens with
    // the pure-mode domain byte and an empty-context length (Alg 24)
    localparam int unsigned MODE_CTX_W = 16;

    typedef struct packed {
        logic [SLH_NW-1:0]           r;
        logic [SLH_NW-1:0]           seed;
        logic [SLH_NW-1:0]           root;
        logic [MODE_CTX_W-1:0]       mode_ctx;
        logic [arith_pkg::WIDTH-1:0] message;
    } slh_hmsg_msg_t;

    // H_msg, outer hash: MGF1 over R || PK.seed || inner digest, one counter
    // value since m fits in one SHA-256 output
    localparam int unsigned MGF1_COUNTER_W = 32;

    typedef struct packed {
        logic [SLH_NW-1:0]         r;
        logic [SLH_NW-1:0]         seed;
        logic [sha2_wrap_pkg::SHA256_DIGEST_W-1:0] inner_digest;
        logic [MGF1_COUNTER_W-1:0] counter;
    } slh_mgf1_msg_t;

    // The H_msg digest (Alg 20 lines 9-13): md, then idx_tree and idx_leaf
    // as whole bytes of which the low bits are used; the rest of the SHA-256
    // output lies beyond the m bytes of the digest
    localparam int unsigned SLH_TREE_FIELD_W = 8 * ((SLH_IDX_TREE_W + 7) / 8);
    localparam int unsigned SLH_LEAF_FIELD_W = 8 * ((SLH_IDX_LEAF_W + 7) / 8);
    localparam int unsigned SLH_BEYOND_M_W   = sha2_wrap_pkg::SHA256_DIGEST_W - SLH_MD_W
                                             - SLH_TREE_FIELD_W - SLH_LEAF_FIELD_W;

    typedef struct packed {
        logic [SLH_MD_W-1:0]         md;
        logic [SLH_TREE_FIELD_W-1:0] tree_field;
        logic [SLH_LEAF_FIELD_W-1:0] leaf_field;
        logic [SLH_BEYOND_M_W-1:0]   beyond_m;
    } slh_digest_t;

endpackage
